site_name: AVWX
site_author: Michael duPont
repo_url: https://github.com/avwx-rest/avwx-engine

nav:
  - Getting Started: getting-started.md
  - Aviation:
    - METAR: av/metar.md
    - TAF: av/taf.md
    - PIREP: av/pirep.md
  - Models:
    - GFS MOS MAV: gfs/mav.md
    - GFS MOS MEX: gfs/mex.md
  - Utilities:
    - Station: util/station.md
    - Data Services: util/service.md
    - Data Structures: util/structs.md
    - Static Values: util/static.md
    - Exceptions: util/exceptions.md

# theme:
#   name: 'material'
#   language: 'en'
#   logo:
#     icon: 'flight'

plugins:
  - search
  - minify:
      minify_html: true